-- MySQL Script generated by MySQL Workbench
-- Thu Jun 20 14:57:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema almacen
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `almacen` ;

-- -----------------------------------------------------
-- Schema almacen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `almacen` DEFAULT CHARACTER SET utf8 ;
USE `almacen` ;

-- -----------------------------------------------------
-- Table `almacen`.`permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almacen`.`permisos` ;

CREATE TABLE IF NOT EXISTS `almacen`.`permisos` (
  `idRol` INT(2) NOT NULL,
  `verInventario` INT(2) NULL,
  `agregarProducto` INT(2) NULL,
  `aumentarInventario` INT(2) NULL,
  `cambiarEstatus` INT(2) NULL,
  `verSalidaProductos` INT(2) NULL,
  `sacarInventario` INT(2) NULL,
  `verHistorico` INT(2) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacen`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almacen`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `almacen`.`usuarios` (
  idUsuario INT(6) NOT NULL,
  nombre VARCHAR(100) NULL,
  correo VARCHAR(50) NULL,
  contrasena VARCHAR(25) NULL,
  idRol INT(2) NULL,
  estatus INT(1) NULL,
  PRIMARY KEY (idUsuario),
  CONSTRAINT `fk_usuarios_permisos1`
    FOREIGN KEY (idRol)
    REFERENCES `almacen`.`permisos` (idRol)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `almacen`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almacen`.`productos` ;

CREATE TABLE IF NOT EXISTS `almacen`.`productos` (
  `idProducto` INT(6) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `cantidad` INT(10) NULL,
  `estatus` INT(2) NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacen`.`historico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almacen`.`historico` ;

CREATE TABLE IF NOT EXISTS `almacen`.`historico` (
  `idMovimiento` INT(6) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(8) NULL,
  `idUsuario` INT(6) NULL,
  `fechaHora` VARCHAR(45) NULL,
  `idProducto` INT(6) NULL,
  `cantidad` INT(10) NULL,
  PRIMARY KEY (`idMovimiento`),
  CONSTRAINT `fk_historico_productos`
    FOREIGN KEY (`idProducto`)
    REFERENCES `almacen`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `almacen`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- INSERTS FOR TABLE PERMISOS 
-- -----------------------------------------------------
# idRol, (1) => Administrador, (2) => Almacenista
#para los demas campos (1) => true, (0) => false
insert into almacen.permisos (`idRol`,`verInventario`,`agregarProducto`,`aumentarInventario`
,`cambiarEstatus`,`verSalidaProductos`,`sacarInventario`,`verHistorico`) 
values (1,1,1,1,1,0,0,1);
insert into almacen.permisos values(2,1,0,0,0,1,1,0);

-- -----------------------------------------------------
-- INSERTS FOR TABLE USUARIOS 
-- -----------------------------------------------------
insert into almacen.usuarios (idUsuario, nombre, correo, contrasena, idRol, estatus) 
values(1,'Leonardo Orozco','leo@gmail.com','1234',1,1);
insert into almacen.usuarios (idUsuario, nombre, correo, contrasena, idRol, estatus)
values (2,'John Smith','smith@gmail.com','1234',2,1);

-- -----------------------------------------------------
-- INSERTS FOR TABLE PRODUCTOS
-- -----------------------------------------------------
insert into almacen.productos (idProducto,nombre,cantidad,estatus) 
values(1,"producto 1",100,1);
insert into almacen.productos (idProducto,nombre,cantidad,estatus) 
values(2,"producto 2",200,1);
insert into almacen.productos (idProducto,nombre,cantidad,estatus) 
values(3,"producto 3",300,1);

-- test autoincrement
insert into almacen.productos (nombre,cantidad,estatus) 
values("producto 4",0,0);
-- test update
update almacen.productos set cantidad=400 where idProducto=4;
-- -----------------------------------------------------
-- SELECT'S
-- -----------------------------------------------------
select * from almacen.productos;
select * from almacen.usuarios;
select * from almacen.historico;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
